# Generated by Django 5.1.2 on 2024-10-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0002_player_totalscores_tournament_tournamentrank"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="gameCode",
            new_name="roomCode",
        ),
        migrations.AddField(
            model_name="room",
            name="privateRoom",
            field=models.BooleanField(default=False),
        ),
    ]
