# Generated by Django 5.1.2 on 2024-11-01 01:31

from django.db import migrations, models

def checkAvailableRooms(apps, schema_editor):
    room = apps.get_model("room", "Room")

    room.objects.get_or_create(id="Room4", roomName="Sala4", maxAmountOfPlayers=4, roomCode=4)
    room.objects.get_or_create(id="Room5", roomName="Sala5", maxAmountOfPlayers=4, roomCode=5)
    room.objects.get_or_create(id="Room6", roomName="Sala6", maxAmountOfPlayers=4, roomCode=6)
    room.objects.get_or_create(id="Room7", roomName="Sala7", maxAmountOfPlayers=4, roomCode=7)
    room.objects.get_or_create(id="Room8", roomName="Sala8", maxAmountOfPlayers=4, roomCode=8)
    room.objects.get_or_create(id="Room9", roomName="Sala9", maxAmountOfPlayers=4, roomCode=9)
    room.objects.get_or_create(id="Room10", roomName="Sala10", maxAmountOfPlayers=4, roomCode=10)
    room.objects.get_or_create(id="Room11", roomName="Sala11", maxAmountOfPlayers=4, roomCode=11)
    room.objects.get_or_create(id="Room12", roomName="Sala12", maxAmountOfPlayers=4, roomCode=12)
    room.objects.get_or_create(id="Room13", roomName="Sala13", maxAmountOfPlayers=4, roomCode=13)
    room.objects.get_or_create(id="Room14", roomName="Sala14", maxAmountOfPlayers=4, roomCode=15)
    room.objects.get_or_create(id="Room15", roomName="Sala15", maxAmountOfPlayers=4, roomCode=15)

class Migration(migrations.Migration):

    dependencies = [
        ("room", "0003_rename_gamecode_room_roomcode_room_privateroom"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "matchId",
                    models.CharField(
                        editable=False, max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("roomCode", models.CharField(max_length=64)),
                ("maxAmountOfPlayers", models.IntegerField(default=1)),
                ("amountOfPlayers", models.IntegerField(default=1)),
                ("matchStatus", models.IntegerField(default=0)),
                ("matchWinner", models.CharField(max_length=100)),
                ("createdBy", models.CharField(max_length=64)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedBy", models.CharField(max_length=64)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="player",
            name="matchId",
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.RunPython(checkAvailableRooms),
    ]
