# Generated by Django 5.1.2 on 2025-06-14 19:06
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_alter_matchplayer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='userId',
            field=models.CharField(db_index=True, default=uuid.uuid4(), editable=False, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
