# Generated by Django 5.2.3 on 2025-06-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_player_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='userId',
            field=models.CharField(db_index=True, editable=False, max_length=64),
        ),
    ]
