# Generated by Django 5.1.2 on 2024-10-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("roomName", models.CharField(max_length=100)),
                ("maxAmountOfPlayers", models.IntegerField(default=2)),
                ("amountOfPlayers", models.IntegerField(default=1)),
                ("roomType", models.IntegerField(default=0)),
                ("roomStatus", models.IntegerField(default=0)),
                ("createdBy", models.CharField(max_length=64)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedBy", models.CharField(max_length=64)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("gameCode", models.CharField(max_length=64)),
            ],
        ),
    ]
