# Generated by Django 5.1.2 on 2024-10-26 21:47

from django.db import migrations, models

def create_initial_rooms(apps, schema_editor):
    # Obter o modelo Room de forma dinâmica para evitar problemas de importação direta
    ctxRoom = apps.get_model("rooms", "Room")

    # Criar ou obter dados iniciais
    ctxRoom.objects.get_or_create(id="Room1", defaults={"roomName": "Sala1", "roomStatus": 0})
    ctxRoom.objects.get_or_create(id="Room2", defaults={"roomName": "Sala2", "roomStatus": 2})
    ctxRoom.objects.get_or_create(id="Room3", defaults={"roomName": "Sala3", "roomStatus": 3})

class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "playerId",
                    models.CharField(
                        editable=False, max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("playerName", models.CharField(max_length=100)),
                ("roomCode", models.CharField(max_length=64)),
                ("profileColor", models.IntegerField(default=0)),
                ("urlProfileImage", models.CharField(max_length=100)),
                ("createdBy", models.CharField(max_length=64)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedBy", models.CharField(max_length=64)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TotalScores",
            fields=[
                (
                    "playerId",
                    models.CharField(
                        editable=False, max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("createdBy", models.CharField(max_length=64)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedBy", models.CharField(max_length=64)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "tournamentCode",
                    models.CharField(
                        editable=False, max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("numberOfGames", models.IntegerField(default=0)),
                ("amountOfPlayers", models.IntegerField(default=0)),
                ("tournamentWinner", models.CharField(max_length=100)),
                ("createdBy", models.CharField(max_length=64)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedBy", models.CharField(max_length=64)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TournamentRank",
            fields=[
                (
                    "playerId",
                    models.CharField(
                        editable=False, max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("tournamentCode", models.CharField(editable=False, max_length=64)),
                ("rankPosition", models.IntegerField(default=0)),
                ("numberOfGamesPlayed", models.IntegerField(default=0)),
            ],
        ),
        migrations.RunPython(create_initial_rooms),
    ]
