# Generated by Django 5.1.2 on 2024-11-03 22:40

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_match_player_matchid"),
    ]

    operations = []