# Generated by Django 5.1.2 on 2024-11-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0005_rename_app"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
